name: br_ipti_tag_app
description: TAG - Tecnologia de Apoio a gestão

publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.6.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:   
  collection: ^1.15.0  
  dartz: any
  device_preview: any
  dio: any
  equatable: ^2.0.3
  firebase_core: 1.17.1
  firebase_crashlytics: 2.8.1
  firebase_performance: 0.8.0+13
  flutter:
    sdk: flutter  
  flutter_bloc: ^7.0.1
  flutter_modular: ^5.0.3
  flutter_svg: any  
  form_field_validator: any  
  meta: ^1.1.6
  package_info_plus: 1.4.2
  shared_preferences: ^2.0.8
  tag_ui:
    path: ../tag_ui
  url_launcher: ^6.0.12

dev_dependencies:
  change_app_package_name: ^1.1.0
  dart_code_metrics: ^4.19.1
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  lint: ^1.0.0
  mocktail: ^0.3.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo/logo_tag.svg
    - assets/dumb_data/meals_of_day.json
    - assets/dumb_data/stock.json
    - assets/icons/home/azul.svg
    - assets/icons/home/cinza.svg
    - assets/icons/pessoas/azul.svg
    - assets/icons/pessoas/cinza.svg
    - assets/icons/lapis/azul.svg
    - assets/icons/lapis/cinza.svg
    - assets/icons/onibus/azul.svg
    - assets/icons/onibus/cinza.svg
    - assets/icons/maca/azul.svg
    - assets/icons/maca/cinza.svg
    - assets/icons/info/info.svg
    - assets/icons/fechar/fechar.svg
    - assets/icons/impressora/impressora.svg
    - assets/resources/tag_logo_for_background.svg
   

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  