name: tag_sdk
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com
publish_to: 'none'


environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.17.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  flutter_test:
    sdk: flutter  
  mocktail: ^0.3.0

dependencies:
  collection: ^1.16.0
  dartz: ^0.10.1
  flutter_modular: ^5.0.3  
  shared_preferences: ^2.0.8
  tag_network:    
    path: ../tag_network
  flutter:
    sdk: flutter
  equatable: ^2.0.5


flutter: