name: tag_ui
description: Componentes de interface de usuário do TAG (Tecnologia de apoio a gestão).
version: 0.26.0
repository: https://github.com/ipti/br.tag.app.ui

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  mask_text_input_formatter: ^2.3.0  
  flutter_svg: ^1.0.3
  equatable: ^2.0.3  
  flutter:
    sdk: flutter
  multi_select_flutter: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockingjay: ^0.3.0
  mocktail: ^0.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:    
    - packages/tag_ui/assets/logo/logo_grey_tag.svg
    - packages/tag_ui/assets/logo/logo_light_tag.svg
    - packages/tag_ui/assets/logo/logo_tag.svg
    
    
    - packages/tag_ui/assets/icons/home/azul.svg
    - packages/tag_ui/assets/icons/home/cinza.svg
    - packages/tag_ui/assets/icons/pessoas/azul.svg
    - packages/tag_ui/assets/icons/pessoas/cinza.svg
    - packages/tag_ui/assets/icons/lapis/azul.svg
    - packages/tag_ui/assets/icons/lapis/cinza.svg
    - packages/tag_ui/assets/icons/onibus/azul.svg
    - packages/tag_ui/assets/icons/onibus/cinza.svg
    - packages/tag_ui/assets/icons/maca/azul.svg
    - packages/tag_ui/assets/icons/maca/cinza.svg
    - packages/tag_ui/assets/icons/info/info.svg
    - packages/tag_ui/assets/icons/fechar/fechar.svg
    - packages/tag_ui/assets/icons/impressora/impressora.svg
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
