name: Generate firebase configurations

on:
  workflow_call:
    inputs:
      runs_on:
        required: false
        type: string
        default: "ubuntu-latest"     
      environment:
        required: false
        type: string
        default: "development"
      working_directory:
        required: false
        type: string
        default: "."
      flutter_version:
        type: string
        default: '3.3.5'
       

jobs:
  build:      
    runs-on: ${{ inputs.runs_on }}    
    env:
      ENVIRONMENT: ${{ inputs.environment }}
    steps:
      - name: 🔽 Get project folder from artifacts
        id: project-folder
        uses: actions/download-artifact@v2
        with:
          name: project_folder
          
      - name: ☕ Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: 🐦 Setup Flutter        
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ inputs.flutter_version }}
          channel: 'stable'
          
      - name: 🔑 Decode Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: key.jks
          encodedString: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      
      - name: ⚙ Create key.properties
        working-directory: ${{ steps.project-folder.outputs.download-path }}/apps/br_ipti_tag_app
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> android/key.properties
      
      - name: 📦 Download pub dependencies
        working-directory: ${{ steps.project-folder.outputs.download-path }}/apps/br_ipti_tag_app
        run: flutter pub get

      - name: 🏃 Running coding genarate
        working-directory: ${{ steps.project-folder.outputs.download-path }}/packages/tag_sdk
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: 🤖 Build Android App Bundle
        working-directory: ${{ steps.project-folder.outputs.download-path }}/apps/br_ipti_tag_app
        run: flutter build appbundle
      
      - name: 🔼 Upload Android App Bundle
        uses: actions/upload-artifact@v2
        with:
          name: appbundle
          path: ${{ steps.project-folder.outputs.download-path }}/apps/br_ipti_tag_app/build/app/outputs/bundle/release/app-release.aab       
