name: Generate firebase configurations

on:
  workflow_call:
    secrets:
      ANDROID_KEYSTORE_BASE64:
        required: true
      ANDROID_KEYSTORE_PASSWORD:
        required: true
      ANDROID_KEY_PASSWORD:
        required: true
      ANDROID_KEY_ALIAS:
        required: true

jobs:
  build-android:
    name: Build Android   
    runs-on: ubuntu-latest
    steps:
      - name: Get project folder from artifacts
        id: project-folder
        uses: actions/download-artifact@v2
        with:
          name: project_folder
          

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      
      - name: Cache pub dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.FLUTTER_HOME }}/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-pub-

      - name: Setup Flutter        
        uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
          
      - name: Decode Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: key.jks
          encodedString: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      
      - name: Create key.properties
        working-directory: ${{ steps.project-folder.outputs.download-path }}/br_ipti_tag_app
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> android/key.properties
      
      - name: Download pub dependencies
        working-directory: ${{ steps.project-folder.outputs.download-path }}/br_ipti_tag_app
        run: flutter pub get

      - name: Build Android App Bundle
        working-directory: ${{ steps.project-folder.outputs.download-path }}/br_ipti_tag_app
        run: flutter build appbundle
      
      - name: Upload Android App Bundle
        uses: actions/upload-artifact@v2
        with:
          name: appbundle
          path: ${{ steps.project-folder.outputs.download-path }}/br_ipti_tag_app/build/app/outputs/bundle/release/app-release.aab       
