name: Bump Version

on:
  push:
    branches:
      - develop
      - 'ci/deploy_playstore'
jobs:
  release-please:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:      
      - name: Bump Version
        id: bump_version
        uses: google-github-actions/release-please-action@v3
        with:
          path: br_ipti_tag_app
          release-type: dart          
          package-name: br_ipti_tag_app          
          command: github-release
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Update version in YAML
        working-directory: ./br_ipti_tag_app
        run: |          
          dart pub global activate cider
      
      - name: Upgrade Major version        
        if:  startsWith(github.github.ref_name, 'ci')
        run: cider bump major
      
      - name: Upgrade Minor version
        if:  startsWith(github.github.ref_name, 'fix')
        run: cider bump minor
      
      - name: Check Version
        run: cider version
