name: Bump Version

on:
  push:
    branches:
      - develop
      - 'ci/deploy_playstore'
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:      
      - name: Bump Version
        id: bump_version
        uses: google-github-actions/release-please-action@v3
        with:
          path: br_ipti_tag_app
          release-type: dart          
          package-name: br_ipti_tag_app          
          command: github-release
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.10.4'

      - name: Cache pub dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.FLUTTER_HOME }}/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-pub-

      - name: Update version in YAML
        working-directory: ./br_ipti_tag_app
        run: |          
          pub global activate cider
      
      - name: Upgrade Major version        
        if:  startsWith(github.head_ref, 'ci/')
        run: cider bump major
      
      - name: Upgrade Minor version
        if:  startsWith(github.head_ref, 'fix/')
        run: cider bump minor
      
      - name: Check Version
        run: cider version
