name: Bump Version

on:
  push:
    branches:
      - develop
      - 'ci/deploy_playstore'
jobs:
  release-please:
    runs-on: ubuntu-latest    
    steps:      
      - name: Bump Version
        id: bump_version
        uses: google-github-actions/release-please-action@v3
        with:
          path: br_ipti_tag_app
          release-type: dart          
          package-name: br_ipti_tag_app          
          command: github-release
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1.3

      - name: Update version in YAML
        working-directory: ./br_ipti_tag_app
        run: |          
          dart pub global activate cider
      
      - name: Upgrade Major version
        working-directory: ./br_ipti_tag_app
        if:  startsWith(github.ref_name, 'ci')
        run: cider bump major
      
      - name: Upgrade Minor version
        working-directory: ./br_ipti_tag_app
        if:  startsWith(github.ref_name, 'fix')
        run: cider bump minor
      
      - name: Check Version
        working-directory: ./br_ipti_tag_app
        run: cider version
