name: Bump Version

on:
  push:
    branches:      
      - 'ci/deploy_playstore'
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          path: ./br_ipti_tag_app
          release-type: dart          
          package-name: br_ipti_tag_app