name: CI

on:
  pull_request:
    branches:
      - main
    types:      
      - opened
      - synchronize
      - edited

jobs:
  build:
    name: Check Semantic Version PR
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3      
      - uses: amannn/action-semantic-pull-request@v4
        id: verify_pull

      - name: Conventional Changelog Action        
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:          
          github-token: ${{ secrets.GH_TOKEN_ACTION }}
          output-file: br_ipti_tag_app/CHANGELOG.md
          version-file: br_ipti_tag_app/pubspec.yaml

        