name: Generate firebase configurations

on:
  workflow_call:
    inputs:
      runs_on:
        required: false
        type: string
        default: "ubuntu-latest"     
      environment:
        required: false
        type: string
        default: "development"
       
jobs:
  build:      
    runs-on: ${{ inputs.runs_on }}
    # environment: ${{ inputs.environment }}
    steps:
      - name: 🔽 Get appbundle from artifacts
        id: appbundle-download
        uses: actions/download-artifact@v2
        with:
          name: appbundle
      
      - name: 🚀 Release on Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.3     
        with:
          appId: ${{secrets.FIREBASE_ANDROID_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}} 
          groups: teste-interno
          file: ${{ steps.appbundle-download.outputs.download-path }}/app-release.aab