name: Deploy for Internal Test

on:
  push:
    branches:
      - develop
      - 'ci/deploy_playstore'
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [develop]
  
jobs:
  generate_firebase_files:
    name: 'Generate Firebase Files'
    uses: ./.github/workflows/generate_firebase_files.yml
    secrets: inherit
    with: 
      working_directory: ./br_ipti_tag_app
      workspace: "${{ github.workspace }}"
      firebase-project: br-org-ipti-tag
    
   
################ Start Android pipeline ################## 

  build-android:
    needs: generate_firebase_files
    uses: ./.github/workflows/build_android.yml
    name: Build Android
    secrets: inherit                      

  android-deploy:
    name: Deploy Android to App Distribution
    runs-on: ubuntu-latest
    needs: build-android
    environment: development
    steps:
      - name: Get appbundle from artifacts
        id: appbundle-download
        uses: actions/download-artifact@v2
        with:
          name: appbundle
      
      - name: Release on Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.3     
        with:
          appId: ${{secrets.FIREBASE_ANDROID_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}} 
          groups: teste-interno
          file: ${{ steps.appbundle-download.outputs.download-path }}/app-release.aab

################ End Android pipeline ##################

################ Start Web pipeline ##################

  build-web:
    name: Build Web
    needs: generate_firebase_files   
    runs-on: ubuntu-latest
    steps:
      - name: Get project folder from artifacts
        id: project-folder
        uses: actions/download-artifact@v2
        with:
          name: project_folder
      

      - name: Setup Flutter        
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 2.10.4
          cache: true
          
      - name: Download pub dependencies
        working-directory: ${{ steps.project-folder.outputs.download-path }}/br_ipti_tag_app
        run: flutter pub get

      - name: Build Web App
        working-directory: ${{ steps.project-folder.outputs.download-path }}/br_ipti_tag_app
        run: flutter build web --release
      
      - name: Upload Web App Bundle
        uses: actions/upload-artifact@v2
        with:
          name: webbundle
          path: |
            ${{ steps.project-folder.outputs.download-path }}/br_ipti_tag_app/build/web/
            ${{ steps.project-folder.outputs.download-path }}/br_ipti_tag_app/firebase.json       
  
  web-deploy:
    name: Deploy to Firebase Hosting
    needs: build-web   
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Get Web Bundle from artifacts
        id: webbundle
        uses: actions/download-artifact@v2
        with:
          name: webbundle

      - name: List Files Downloaded
        run: ls -R
      
      - name: Deploy to Firebase Hosting         
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BR_ORG_IPTI_TAG }}'
          projectId: ${{secrets.FIREBASE_PROJECT_ID }}
          expires: 30d
          channelId: internal
          
################ End Web pipeline ##################