name: Generate firebase configurations

on:
  workflow_call:
    inputs:
      runs_on:
        required: false
        type: string
        default: "ubuntu-latest"
      workspace:
        required: true
        type: string
      environment:
        required: false
        type: string
        default: "development"
      working_directory:
        required: false
        type: string
        default: "."
    


      
jobs:
  build:
    runs-on: ${{ inputs.runs_on }}
    environment: ${{ inputs.env }}
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
          
      - name: 🎯 Setup Dart 
        uses: dart-lang/setup-dart@v1

      - name: 🔥 Setup Firebase-tools
        run: |
          sudo npm install -g firebase-tools
          
      - name: Clone flutterfire_cli docs repository
        uses: actions/checkout@v2        
        with:
          repository: exaby73/flutterfire_cli           
          ref: 'feature/token-option'
          path: 'flutterfire'
      
      - name: ❤️ Show Files
        run: ls -la

      - name: ❤️‍🔥 Setup Flutterfire
        working-directory: flutterfire
        run: |
          dart pub global activate --source="path" . --executable="flutterfire" --overwrite

      - name: 👩‍🚒 Generate Firebase Configuration Files
        working-directory: ${{inputs.working_directory}}
        run: |          
          flutterfire configure --project=${{ secrets.FIREBASE_ANDROID_APP_ID }} --platforms='android,ios,web' --android-package-name="${{secrets.ANDROID_PACKAGE_NAME}}" --ios-bundle-id=br.org.ipti.tag --macos-bundle-id=br.org.ipti.tag --token="${{ secrets.FIREBASE_TOKEN }}" -y
      
      - name: 🔼 Upload folder to build
        uses: actions/upload-artifact@v3
        with:
          name: project_folder
          path: ${{inputs.working_directory}}